### ISSUE TITLE
`createdAt` and `updatedAt` attributes currently not supported in Database Models

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/mockBee#12]
In the MongoDB database, the date-time tracking is relatively simpler. While in present case, adding date-time support will be a good feature as User would get more information about the actions on the app.

**Comment by supminn** [comment]
I wish to work on this. Can you assign this issue to me

**Comment by sohamsshah** [comment]
Hey @supminn , thank you so much! Sure, it would be of great help
