### ISSUE TITLE
Password also used for creating JWT Token

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/mockBee#35]
Password is not necessary to be inserted in the token. We can consider having _id and email/username for creating token. Consider removing it.

**Comment by hmn53** [comment]
Hey. Can I try this ?

**Comment by sohamsshah** [comment]
Sure! Everything related to Auth can be found in `apps/*/src/backend/controllers/AuthController.js`, `apps/*/src/backend/utils/authUtils.js`, `apps/*/src/server.js`. The JWT uses a token which we store in `.env` file. Make sure you add .env file and after changing test the working thoroughly. Thanks and feel free to ping for any assistance required for tackling this issue.
