### ISSUE TITLE
Password encryption is missing on user authentication

### ISSUE THREAD

**Issue by supminn** [neogcamp/mockBee#63]
**Describe the bug**
Currently, the user entered password is stored within the database as is. For security purposes, we would need to encrypt the password and then store it in the database.

**Steps to fix this issue**
We can make use of `bcrypt` to salt and hash the password.

**Comment by supminn** [comment]
I am working on this issue, could you please assign it to me.

**Comment by sohamsshah** [comment]
This looks a great addition. Thanks for this!
