### ISSUE TITLE
[DOCS]: Add the docs for the added endpoint: `/api/users/bookmark` 

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/mockBee#73]
The PR #71 adds a new endpoint: `/api/users/bookmark`. Corresponding documentation shall be added in the docsite.

**Comment by supminn** [comment]
Hi @sohamsshah,

I have updated the documentation to include this new endpoint.
You can refer [here](https://github.com/neogcamp/mockBee/commit/31437707024b7b406d9edb8a97880e5828343990)

**Comment by sohamsshah** [comment]
Oopsie, my bad. Thanks!
