### ISSUE TITLE
A improvement in the Introduction Docs Page

### ISSUE THREAD

**Issue by Ankur9669** [neogcamp/mockBee#81]
**Describe the bug**
So for installation, I followed the steps as it is written in the docs i.e

![image](https://user-images.githubusercontent.com/65125998/158050848-bb0369bc-000e-41a1-b3ff-7755da1e18c9.png)

After doing this step it asked for the Project Name which i entered

After doing this step it asked for the template to which i selected ecommerce

After that I typed npm start and it did not run, the reason for that was i did not cd into my newly made project
## **Suggestion: So we can add in the docs that you need to cd into your newly made directory**

So i figured this out and i cd into my directory, and i ran npm start and it gave me this error

![image](https://user-images.githubusercontent.com/65125998/158050940-37948370-b24c-4a1d-b53b-aed9f5ad538a.png)

So i figured this out reading the error that **we also need to run npm install before running npm start**. But i was not able to find this in the docs. So if we can add this in the docs it would become more beginner friendly.

## **Suggestion: So we can add in the docs that you need to run npm install command to install the node modules before running npm start**

This is the first issue raised by me ever, so please forgive the mistakes that i might have done in explaining the bug

**Comment by sohamsshah** [comment]
This looks a good addition. Feel free to raise a PR!
