### ISSUE TITLE
Updation Needed in Documentation  for MockBee

### ISSUE THREAD

**Issue by manojsarna** [neogcamp/mockBee#88]
In the documentation you have mentioned this...

![image](https://user-images.githubusercontent.com/79917843/158330308-75cdce2d-9458-415b-9911-055213fe60ef.png)

But , in the API we are destructuring product not cart in CartController.js

![image](https://user-images.githubusercontent.com/79917843/158331389-f0b37a9f-6572-4e1a-be30-2e204996a4fa.png)

**Comment by sohamsshah** [comment]
Yes, valid issue. Would you like to make this change? @manojsarna

**Comment by supminn** [comment]
Thanks @manojsarna for letting us know. We are working on getting this fixed.
