### ISSUE TITLE
Wrong Status code for wrong password in E-Commerce app

### ISSUE THREAD

**Issue by SJTGSHIVAM** [neogcamp/mockBee#90]
**Describe the bug**
This is related to the Ecomm app, Auth controller 
line: https://github.com/neogcamp/mockBee/blob/1026d6427ca81da65d3b5dc67d3b5e86f45519cc/apps/e-commerce/src/backend/controllers/AuthController.js#L80
A return statement is missing which is causing status 201 on the wrong password instead of 401.

**To Reproduce**
try to log in with the correct email but the wrong password.

**Expected behavior**
Error with status 401 should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/32888608/158440581-b97af5e6-2fc1-47a5-aa34-6ca860c8d6e3.png)

**Additional context**
Original code looks somewhat like this
![image](https://user-images.githubusercontent.com/32888608/158440984-c7e85e1d-7483-41d5-b664-b2e89569756d.png)

adding a return statement on line number 92 fixes the issue for me:
![image](https://user-images.githubusercontent.com/32888608/158441151-efd339cc-f58d-4b53-aa68-37d20cfc6e20.png)

**Comment by hsnice16** [comment]
The same issue, I faced. And also notice that a return statement is missing.

**Comment by supminn** [comment]
Thanks @SJTGSHIVAM for letting us know. We shall get this fixed.
