### ISSUE TITLE
Variable naming in API documentation for E-Commerce

### ISSUE THREAD

**Issue by foolhardy21** [neogcamp/mockBee#91]
This is a variable naming bug. In the documentation's code snippet, it says `wishList` is returned in `response.data` but the handler is actually returning `wishlist`. 

- Here is the screenshot of documentation
![w-d](https://user-images.githubusercontent.com/79531287/158647822-25ff0cdd-3981-45ec-acdb-0b9a13991eac.png)

- Here is the screenshot of the handler code
![w-c](https://user-images.githubusercontent.com/79531287/158647847-47fdadb2-7859-41db-83d8-4681b27b70ed.png)

Please confirm. Thanks.

**Comment by supminn** [comment]
Thanks, @foolhardy21 for letting us know. We are working on getting this fixed.
