### ISSUE TITLE
Need to update documentation for wishlist api. 

### ISSUE THREAD

**Issue by muskanbagrecha** [neogcamp/mockBee#92]
1. As per docs, the response body of the add to wishlist endpoint will be as such:
![image](https://user-images.githubusercontent.com/46674359/159121271-6283f474-fdc9-44b5-8834-f581d6ff9db7.png)

But it needs to be rectified to :
```js
{
  data : {
     wishlist : Array;
  }
}
```
![image](https://user-images.githubusercontent.com/46674359/159121330-45af0651-2113-402e-a090-97fc1ce6ee50.png)

**Comment by supminn** [comment]
Thanks, @muskanbagrecha for letting us know. We are working on getting this fixed.
